[build]
  base = "/"
  publish = ".next"
  command = "npm run build"
  functions = "/netlify"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-inline-functions-env"
  [plugins.inputs]
    buildEvent = "onBuild"